import Head from "next/head"
import { Inter } from "next/font/google"
import NavBar from "~/components/NavBar"
import { UserPrograms } from "~/components/UserPrograms"
import { supabase } from "~/../supabase"

const inter = Inter({ subsets: ["latin"] })

export default async function Home() {
  const {
    data: { session },
  } = await supabase.auth.getSession()
  return (
    <>
      <Head>
        <title>Usuals - Your Favorite Businesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {session && <UserPrograms user={session.user.id} />}
    </>
  )
}
