"use client"
import Head from "next/head"
import { Inter } from "next/font/google"
import NavBar from "~/components/NavBar"
import BusinessSearch from "~/components/BusinessSearch"
import { MagnifyingGlassIcon } from "@heroicons/react/24/outline"
import { useState } from "react"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const [openSearch, setOpenSearch] = useState(true)
  return (
    <>
      <Head>
        <title>Usuals - Your Favorite Businesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {!openSearch && (
        <div className="flex justify-center items-center mt-5">
          <button
            type="button"
            className="inline-flex items-center gap-x-2 rounded-md bg-gray-200 w-3/4 h-12 text-base font-semibold text-gray-700 shadow-sm px-5"
            onClick={() => setOpenSearch(true)}
          >
            <MagnifyingGlassIcon
              className="-ml-0.5 h-6 w-6"
              aria-hidden="true"
            />
            Search...
          </button>
        </div>
      )}
      <BusinessSearch />
    </>
  )
}
