import Head from "next/head"
import { Inter } from "next/font/google"
import { UserCodes } from "../components/UserCodes"
import NavBar from "../components/NavBar"
import createServerClient from "~/utils/supabase-server"
import SignUp from "~/components/SignUp"
const inter = Inter({ subsets: ["latin"] })

export default async function Home() {
  const supabase = createServerClient()
  const {
    data: { session },
  } = await supabase.auth.getSession()

  return (
    <>
      <Head>
        <title>Usuals - Your Favorite Businesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <>
          <NavBar />
          <UserCodes user={session.user.id} />
        </>
      ) : (
        <SignUp />
      )}
    </>
  )
}
