import Head from "next/head"
import { Inter } from "next/font/google"
import NavBar from "../../components/NavBar"
import Program from "../../components/Program"
import { useRouter } from "next/router"
import { useState, useEffect } from "react"
import { supabase } from "../../client"
import { useUser } from "@supabase/auth-helpers-react"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const user = useUser()?.id
  const router = useRouter()
  const [stamps, setStamps] = useState(null)
  if (router.query.businessUUID) {
    console.log(router.query.businessUUID)
  }
  const [businessData, setBusinessData] = useState(null)
  useEffect(() => {
    if (router.query.businessUUID) {
      supabase
        .from("businesses")
        .select("*")
        .eq("id", router.query.businessUUID)
        .single()
        .then((result) => {
          if (result.data) {
            console.log(result.data)
            setBusinessData(result.data)
          }
        })
      supabase
        .from("profiles_businesses")
        .select("stamps")
        .eq("business_id", router.query.businessUUID)
        .eq("user_id", user)
        .single()
        .then((result) => {
          if (result.data) {
            setStamps(result.data.stamps)
          }
        })
    }
  }, [router.query.businessUUID, user])

  return (
    <>
      <Head>
        <title>Usuals - Your Favorite Businesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {session ? <NavBar /> : <SignUp />} */}
      <NavBar />
      <Program businessData={businessData} user={user} stamps={stamps} />
    </>
  )
}
