import Head from "next/head"
import { Inter } from "next/font/google"
import NavBar from "@component/components/NavBar"
import { atom } from "jotai"
import ProgramSSR from "../../components/ProgramSSR"
import { useRouter } from "next/router"
import { useState, useEffect } from "react"
import { supabase } from "../../client"

const inter = Inter({ subsets: ["latin"] })
export const openSearchAtom = atom(true)
export const selectedProgramAtom = atom("")

export default function Home() {
  const router = useRouter()
  if (router.query.businessUUID) {
    console.log(router.query.businessUUID)
  }
  const [businessData, setBusinessData] = useState(null)
  useEffect(() => {
    if (router.query.businessUUID) {
      supabase
        .from("businesses")
        .select("*")
        .eq("id", router.query.businessUUID)
        .single()
        .then((result) => {
          if (result.data) {
            console.log(result.data)
            setBusinessData(result.data)
          }
        })
    }
  }, [router.query.businessUUID])

  return (
    <>
      <Head>
        <title>Usuals - Your Favorite Businesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {session ? <NavBar /> : <SignUp />} */}
      <NavBar />
      <ProgramSSR businessData={businessData} />
    </>
  )
}
