import { useUser } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { supabase } from '../../client'
import NavBar from '../../components/NavBar'

function Business({ business }) {
  // const features = [
  //   {
  //     name: 'Durable',
  //     description:
  //       'The leather cover and machined steel disc binding stand up to daily use for years to come.',
  //   },
  //   {
  //     name: 'Refillable',
  //     description:
  //       'Buy it once and refill as often as you need. Subscribe and save on routine refills.',
  //   },
  //   {
  //     name: 'Thoughtfully designed',
  //     description:
  //       'The comfortable disc binding allows you to quickly rearrange pages or combine lined, graph, and blank refills.',
  //   },
  //   {
  //     name: 'Locally made',
  //     description:
  //       'Responsibly and sustainably made real close to wherever you are, somehow.',
  //   },
  // ]
  const user = useUser().id
  const router = useRouter()
  const joinProgram = async () => {
    await supabase
      .from('member_programs')
      .insert([{ user_id: user }, { business_id: business.id }])
  }
  return (
    <>
      <Head>
        <title>Usuals - Your Favorite Businesses</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <div className='bg-white'>
        <section aria-labelledby='features-heading' className='relative'>
          <div className='aspect-w-3 aspect-h-2 overflow-hidden sm:aspect-w-5 lg:aspect-none lg:absolute lg:h-full lg:w-1/2 lg:pr-4 xl:pr-16'>
            <img
              src={business.logo_url}
              alt='Black leather journal with silver steel disc binding resting on wooden shelf with machined steel pen.'
              className='h-full w-full object-cover object-center lg:h-full lg:w-full'
            />
          </div>
          <div className='mx-auto max-w-2xl px-4 pt-16 pb-24 sm:px-6 sm:pb-32 lg:grid lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8 lg:pt-32'>
            <div className='lg:col-start-2'>
              {/* <h2 id='features-heading' className='font-medium text-gray-500'>
                {business.business_name}
              </h2> */}
              <p className='mt-4 text-4xl font-bold tracking-tight text-gray-900'>
                {business.business_name}
              </p>
              <p className='mt-4 text-gray-500'>
                {business.business_description}
              </p>
              {/* <dl className='mt-10 grid grid-cols-1 gap-y-10 gap-x-8 text-sm sm:grid-cols-2'>
                {features.map((feature) => (
                  <div key={feature.name}>
                    <dt className='font-medium text-gray-900'>
                      {feature.name}
                    </dt>
                    <dd className='mt-2 text-gray-500'>
                      {feature.description}
                    </dd>
                  </div>
                ))}
              </dl> */}
            </div>
          </div>
        </section>
        <div className='relative ml-3 flex justify-center'>
          <button
            type='button'
            className='inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-full shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 my-5'
            onClick={() => {
              joinProgram()
              router.push('/businesses')
            }}
          >
            Join Program
          </button>
        </div>
      </div>
    </>
  )
}

export const getStaticPaths = async () => {
  const { data: businesses } = await supabase.from('businesses').select('id')

  const paths = businesses.map(({ id }) => ({
    params: {
      id: id.toString(),
    },
  }))

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps = async ({ params: { id } }) => {
  const { data: business } = await supabase
    .from('businesses')
    .select('*')
    .eq('id', id)
    .single()
  return {
    props: {
      business,
    },
  }
}

export default Business
