import Head from "next/head"
import { Inter } from "next/font/google"
import NavBar from "@component/components/NavBar"
import BusinessSearch from "@component/components/BusinessSearch"
import { atom, useAtom } from "jotai"
import FakeSearchBar from "../../components/FakeSearchBar"
import Program from "../../components/Program"

const inter = Inter({ subsets: ["latin"] })
export const openSearchAtom = atom(true)
export const selectedProgramAtom = atom("")

export default function Home() {
  return (
    <>
      <Head>
        <title>Usuals - Your Favorite Businesses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {session ? <NavBar /> : <SignUp />} */}
      <NavBar />
      <FakeSearchBar />
      <Program />
      <BusinessSearch />
    </>
  )
}
